export interface CompanyRecord {
  id: string;
  name: string;
  location: string;
  website: string;
  contactPerson: string;
  mobile: string;
  email: string;
  companySize: string;
  numberOfEmployees: string;
  industry: string;
  ctc: string;
  status: "COLD" | "WARM" | "HOT" | "DRIVE_COMPLETED";
  approvalStatus: "PENDING" | "APPROVED" | "REJECTED";
  dateAdded: string;
  placementTeamMember: string;
  recruiter: string;
  jobRole: string;
  jd: string;
  jdPdf: string;
  driveStatus: string;
  placedStudentsCount: number;
  placedStudentsDetails: string;
  archived: boolean;
  
  // Extended fields
  companyType?: string;
  hrName?: string;
  hrEmail?: string;
  hrPhone?: string;
  description?: string;
  jobRoles?: string;
  requiredSkills?: string;
  salaryPackage?: string;
  jobType?: string;
  openPositions?: number;
  eligibilityCriteria?: string;
  companyStatus?: string;
}

export const INITIAL_COMPANY_CSV_DATA: CompanyRecord[] = [
  {
    "id": "C001",
    "name": "TCS",
    "companyType": "MNC",
    "industry": "IT Services",
    "location": "Chennai",
    "website": "https://tcs.com",
    "contactPerson": "Ananya Sharma",
    "mobile": "+91 98765 43210",
    "email": "campus@tcs.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "7.0 LPA",
    "salaryPackage": "7.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Ananya Sharma",
    "jobRole": "Systems Engineer - Digital",
    "jd": "Implement cloud-native enterprise services, CI/CD automated build pipelines, and automated QA testing.",
    "jdPdf": "https://example.com/jd/tcs-digital-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Meena Devi (RTC2024BIT001)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C002",
    "name": "Infosys",
    "companyType": "MNC",
    "industry": "IT Services",
    "location": "Bengaluru",
    "website": "https://infosys.com",
    "contactPerson": "Rohan Das",
    "mobile": "+91 87654 32109",
    "email": "specialisthire@infosys.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "9.5 LPA",
    "salaryPackage": "9.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-05",
    "placementTeamMember": "Placement Director",
    "recruiter": "Rohan Das",
    "jobRole": "Specialist Programmer (Power Programmer)",
    "jd": "Develop complex full-stack microservices using Spring Boot, React, and containerized deployment workflows.",
    "jdPdf": "https://example.com/jd/infosys-sp-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Dinesh Kumar T (RTC2024BCS005)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C003",
    "name": "CodePulse",
    "companyType": "Startup",
    "industry": "Software / Technology",
    "location": "Bengaluru",
    "website": "https://codepulse.ai",
    "contactPerson": "Vikram Singh",
    "mobile": "+91 99887 76655",
    "email": "careers@codepulse.ai",
    "companySize": "50-200 Employees",
    "numberOfEmployees": "150",
    "ctc": "8.0 LPA",
    "salaryPackage": "8.0 LPA",
    "status": "HOT",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-10",
    "placementTeamMember": "Placement Director",
    "recruiter": "Vikram Singh",
    "jobRole": "Full Stack Developer",
    "jd": "Full Stack Developer in startup environment.",
    "jdPdf": "https://example.com/jd/codepulse.pdf",
    "driveStatus": "Scheduled",
    "placedStudentsCount": 0,
    "placedStudentsDetails": "N/A",
    "archived": false,
    "eligibilityCriteria": "70%+"
  },
  {
    "id": "C004",
    "name": "Krea Data Edge",
    "companyType": "Startup",
    "industry": "Data Analytics / AI",
    "location": "Bengaluru",
    "website": "https://kreadataedge.com",
    "contactPerson": "Priya Nair",
    "mobile": "+91 77665 54433",
    "email": "jobs@kreadataedge.com",
    "companySize": "50-100 Employees",
    "numberOfEmployees": "75",
    "ctc": "7.5 LPA",
    "salaryPackage": "7.5 LPA",
    "status": "WARM",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-12",
    "placementTeamMember": "Placement Director",
    "recruiter": "Priya Nair",
    "jobRole": "Data Analyst",
    "jd": "Data Analytics and AI tools development.",
    "jdPdf": "https://example.com/jd/kreadataedge.pdf",
    "driveStatus": "Scheduled",
    "placedStudentsCount": 0,
    "placedStudentsDetails": "N/A",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C005",
    "name": "Google India",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Bengaluru, India",
    "website": "https://careers.google.com",
    "contactPerson": "Google Recruiting",
    "mobile": "+91 80 6721 8000",
    "email": "campus-recruitment@google.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "24.0 LPA",
    "salaryPackage": "24.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-15",
    "placementTeamMember": "Placement Director",
    "recruiter": "Google Campus Relations",
    "jobRole": "Software Engineer - Campus Specialist",
    "jd": "Design and implement scalable distributed software, algorithms, and core backend infrastructure.",
    "jdPdf": "https://example.com/jd/google-sde-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Adithya Venkatesh (RCAS2024BCS011)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C006",
    "name": "Microsoft India",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Hyderabad, India",
    "website": "https://careers.microsoft.com",
    "contactPerson": "Microsoft Recruiting",
    "mobile": "+91 40 6695 0000",
    "email": "university-india@microsoft.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "21.5 LPA",
    "salaryPackage": "21.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-14",
    "placementTeamMember": "Placement Director",
    "recruiter": "Microsoft Campus Relations",
    "jobRole": "Software Engineer - Azure Cloud",
    "jd": "Develop high-throughput cloud microservices, Azure integrations, and hyper-scale telemetry tools.",
    "jdPdf": "https://example.com/jd/microsoft-azure-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Sneha Muralidharan (RTC2024BCS012)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C007",
    "name": "Amazon Development Centre",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Bengaluru, India",
    "website": "https://amazon.jobs",
    "contactPerson": "Amazon Recruiting",
    "mobile": "+91 80 4103 0000",
    "email": "india-campus-hire@amazon.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "19.5 LPA",
    "salaryPackage": "19.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-12",
    "placementTeamMember": "Placement Director",
    "recruiter": "Amazon Campus Relations",
    "jobRole": "Software Development Engineer (SDE-1)",
    "jd": "Build fault-tolerant multi-tier architecture, automated order fulfillment engines, and distributed APIs.",
    "jdPdf": "https://example.com/jd/amazon-sde1-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Rohit Balaji (RCAS2024BIT011)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C008",
    "name": "Amazon Web Services (AWS)",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Bengaluru, India",
    "website": "https://aws.amazon.com/careers",
    "contactPerson": "AWS Recruiting",
    "mobile": "+91 80 4103 0001",
    "email": "aws-university-in@amazon.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "17.0 LPA",
    "salaryPackage": "17.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-10",
    "placementTeamMember": "Placement Director",
    "recruiter": "AWS Campus Relations",
    "jobRole": "Cloud Support Associate - DevOps & Sec",
    "jd": "Triage complex AWS cloud infrastructure, configure VPCs, IAM policies, and infrastructure-as-code.",
    "jdPdf": "https://example.com/jd/aws-cloud-support-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Harini Natarajan (RTC2024BCY011)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C009",
    "name": "Adobe Systems",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Noida, India",
    "website": "https://adobe.com/careers",
    "contactPerson": "Adobe Recruiting",
    "mobile": "+91 120 444 4700",
    "email": "india-ur@adobe.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "16.5 LPA",
    "salaryPackage": "16.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-08",
    "placementTeamMember": "Placement Director",
    "recruiter": "Adobe Campus Relations",
    "jobRole": "Member of Technical Staff - Creative Cloud",
    "jd": "Architect client-side rendering engines, WebAssembly integrations, and high-performance cloud assets.",
    "jdPdf": "https://example.com/jd/adobe-mts-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Varshini Ramesh (RCAS2024BCS013)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C010",
    "name": "Cisco Systems",
    "companyType": "MNC",
    "industry": "Network & Security",
    "location": "Bengaluru, India",
    "website": "https://jobs.cisco.com",
    "contactPerson": "Cisco Recruiting",
    "mobile": "+91 80 4426 0000",
    "email": "university-hiring@cisco.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "15.0 LPA",
    "salaryPackage": "15.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-05",
    "placementTeamMember": "Placement Director",
    "recruiter": "Cisco Campus Relations",
    "jobRole": "Network Security Engineer",
    "jd": "Design and maintain zero-trust enterprise firewalls, automated telemetry, and SD-WAN networks.",
    "jdPdf": "https://example.com/jd/cisco-netsec-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Akash Subramanian (RTC2024BEC011)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C011",
    "name": "Qualcomm India",
    "companyType": "MNC",
    "industry": "Hardware & Embedded",
    "location": "Chennai, India",
    "website": "https://qualcomm.com/careers",
    "contactPerson": "Qualcomm Recruiting",
    "mobile": "+91 44 6612 0000",
    "email": "campus-india@qualcomm.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "14.5 LPA",
    "salaryPackage": "14.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-04",
    "placementTeamMember": "Placement Director",
    "recruiter": "Qualcomm Campus Relations",
    "jobRole": "Firmware & Embedded Security Engineer",
    "jd": "Develop low-level cryptographic microcode, ARM hardware security modules, and bootloader integrity.",
    "jdPdf": "https://example.com/jd/qualcomm-firmware-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Divya Lakshmi (RCAS2024BCY002)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C012",
    "name": "Salesforce India",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Hyderabad, India",
    "website": "https://salesforce.com/careers",
    "contactPerson": "Salesforce Recruiting",
    "mobile": "+91 40 6902 0000",
    "email": "futureforce-india@salesforce.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "13.5 LPA",
    "salaryPackage": "13.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-02",
    "placementTeamMember": "Placement Director",
    "recruiter": "Salesforce Campus Relations",
    "jobRole": "Associate Software Engineer",
    "jd": "Build scalable multi-tenant Apex apps, Lightning Web Components, and enterprise CRM workflow pipelines.",
    "jdPdf": "https://example.com/jd/salesforce-ase-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Gautham Krishna (RTC2024BIT012)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C013",
    "name": "CrowdStrike India",
    "companyType": "MNC",
    "industry": "Cyber Security",
    "location": "Pune, India",
    "website": "https://crowdstrike.com/careers",
    "contactPerson": "CrowdStrike Recruiting",
    "mobile": "+91 20 6710 0000",
    "email": "university@crowdstrike.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "13.0 LPA",
    "salaryPackage": "13.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-28",
    "placementTeamMember": "Placement Director",
    "recruiter": "CrowdStrike Campus Relations",
    "jobRole": "Threat Intelligence Specialist",
    "jd": "Perform reverse engineering of malware payloads, identify threat actors, and author Falcon detections.",
    "jdPdf": "https://example.com/jd/crowdstrike-threat-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 2,
    "placedStudentsDetails": "Abishek M (RCAS2024BCY004), Deepak Chandran (RTC2024BCY012)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C014",
    "name": "Texas Instruments",
    "companyType": "MNC",
    "industry": "Hardware & Embedded",
    "location": "Bengaluru, India",
    "website": "https://ti.com/careers",
    "contactPerson": "TI Recruiting",
    "mobile": "+91 80 2509 9000",
    "email": "india-campus@ti.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "11.0 LPA",
    "salaryPackage": "11.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-25",
    "placementTeamMember": "Placement Director",
    "recruiter": "TI Campus Relations",
    "jobRole": "Hardware & Embedded Systems Trainee",
    "jd": "Design mixed-signal PCB architectures, embedded microcontrollers, and perform digital signal processing.",
    "jdPdf": "https://example.com/jd/ti-embedded-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Ananya Rao (RCAS2024BEC002)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C015",
    "name": "Flipkart",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Bengaluru, India",
    "website": "https://flipkartcareers.com",
    "contactPerson": "Flipkart Recruiting",
    "mobile": "+91 80 4208 0000",
    "email": "campusrelations@flipkart.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "ctc": "11.0 LPA",
    "salaryPackage": "11.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-22",
    "placementTeamMember": "Placement Director",
    "recruiter": "Flipkart Campus Relations",
    "jobRole": "Associate Software Engineer - Supply Chain",
    "jd": "Design warehouse inventory dispatch engines, real-time tracking queues, and high-throughput Kafka streaming.",
    "jdPdf": "https://example.com/jd/flipkart-ase-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Pooja Sundaram (RTC2024BCS014)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C016",
    "name": "Palo Alto Networks",
    "companyType": "MNC",
    "industry": "Cyber Security",
    "location": "Bengaluru, India",
    "website": "https://paloaltonetworks.com/careers",
    "contactPerson": "Palo Alto Recruiting",
    "mobile": "+91 80 6112 0000",
    "email": "india-recruiting@paloaltonetworks.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "ctc": "10.0 LPA",
    "salaryPackage": "10.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-20",
    "placementTeamMember": "Placement Director",
    "recruiter": "Palo Alto Campus Relations",
    "jobRole": "SOC & Cyber Defense Analyst",
    "jd": "Monitor enterprise SOC incidents, analyze firewall logs, and configure automated Cortex XSOAR playbooks.",
    "jdPdf": "https://example.com/jd/paloalto-soc-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Naveen Kumar (RCAS2024BCY001)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C017",
    "name": "Zoho Corporation",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Chennai, India",
    "website": "https://zoho.com/careers",
    "contactPerson": "Zoho Recruiting",
    "mobile": "+91 44 6744 7070",
    "email": "recruitment@zohocorp.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "8.5 LPA",
    "salaryPackage": "8.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-15",
    "placementTeamMember": "Placement Director",
    "recruiter": "Zoho Campus Relations",
    "jobRole": "Application Security Engineer",
    "jd": "Perform SAST/DAST web vulnerability assessments, OAuth security hardening, and code remediation.",
    "jdPdf": "https://example.com/jd/zoho-appsec-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 2,
    "placedStudentsDetails": "INBAVARUNAN S (RCAS2024BCY046), Manoj Prabhakar (RTC2024BCY013)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C018",
    "name": "Deloitte USI",
    "companyType": "MNC",
    "industry": "Consulting / IT",
    "location": "Hyderabad, India",
    "website": "https://deloitte.com/careers",
    "contactPerson": "Deloitte Recruiting",
    "mobile": "+91 40 7125 0000",
    "email": "usiurrecruiting@deloitte.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "7.5 LPA",
    "salaryPackage": "7.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-10",
    "placementTeamMember": "Placement Director",
    "recruiter": "Deloitte Campus Relations",
    "jobRole": "Business Technology Analyst",
    "jd": "Analyze IT architecture workflows, develop enterprise BI dashboards, and support ERP migrations.",
    "jdPdf": "https://example.com/jd/deloitte-bta-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Sanjay Kumar (RCAS2024BBA001)",
    "archived": false,
    "eligibilityCriteria": "65%+"
  },
  {
    "id": "C019",
    "name": "Wipro Digital",
    "companyType": "MNC",
    "industry": "IT Services",
    "location": "Bengaluru, India",
    "website": "https://careers.wipro.com",
    "contactPerson": "Wipro Recruiting",
    "mobile": "+91 80 2844 0011",
    "email": "manager.campus@wipro.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "6.8 LPA",
    "salaryPackage": "6.8 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-05",
    "placementTeamMember": "Placement Director",
    "recruiter": "Wipro Campus Relations",
    "jobRole": "Cyber Defense Analyst",
    "jd": "Coordinate incident response lifecycles, conduct vulnerability remediation, and manage endpoint security.",
    "jdPdf": "https://example.com/jd/wipro-cyber-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Swetha Mohan (RCAS2024BCY003)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C020",
    "name": "Cognizant Technology Solutions",
    "companyType": "MNC",
    "industry": "IT Services",
    "location": "Coimbatore, India",
    "website": "https://cognizant.com/careers",
    "contactPerson": "Cognizant Recruiting",
    "mobile": "+91 422 664 5000",
    "email": "campusconnection@cognizant.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "6.5 LPA",
    "salaryPackage": "6.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-07-02",
    "placementTeamMember": "Placement Director",
    "recruiter": "Cognizant Campus Relations",
    "jobRole": "Programmer Analyst Trainee",
    "jd": "Build scalable frontend interfaces with React/Next.js and maintain PostgreSQL relational databases.",
    "jdPdf": "https://example.com/jd/cognizant-pat-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Vishal Anand (RTC2024BIT002)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C021",
    "name": "HDFC Bank",
    "companyType": "MNC",
    "industry": "Banking & Finance",
    "location": "Mumbai, India",
    "website": "https://hdfcbank.com/careers",
    "contactPerson": "HDFC Recruiting",
    "mobile": "+91 22 6652 1000",
    "email": "campusrecruitment@hdfcbank.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "6.2 LPA",
    "salaryPackage": "6.2 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-06-28",
    "placementTeamMember": "Placement Director",
    "recruiter": "HDFC Campus Relations",
    "jobRole": "Management Trainee - Tech FinOps",
    "jd": "Oversee digital banking operations, credit score automation models, and compliance reporting.",
    "jdPdf": "https://example.com/jd/hdfc-mt-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Keerthana R (RCAS2024BBA002)",
    "archived": false,
    "eligibilityCriteria": "60%+"
  },
  {
    "id": "C022",
    "name": "Oracle India",
    "companyType": "MNC",
    "industry": "Software / Technology",
    "location": "Bengaluru, India",
    "website": "https://oracle.com/careers",
    "contactPerson": "Oracle Recruiting",
    "mobile": "+91 80 4327 0000",
    "email": "campus_india@oracle.com",
    "companySize": "10,000+ Employees",
    "numberOfEmployees": "10000+",
    "ctc": "12.5 LPA",
    "salaryPackage": "12.5 LPA",
    "status": "WARM",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-30",
    "placementTeamMember": "Placement Director",
    "recruiter": "Oracle Campus Relations",
    "jobRole": "Associate Cloud Consultant",
    "jd": "Assist enterprise clients with Oracle Cloud Infrastructure (OCI) architecture and automated database migration.",
    "jdPdf": "https://example.com/jd/oracle-oci-2027.pdf",
    "driveStatus": "Scheduled",
    "placedStudentsCount": 0,
    "placedStudentsDetails": "Upcoming Drive - Shortlisting Stage",
    "archived": false,
    "eligibilityCriteria": "60%+"
  }
];
