export interface CompanyRecord {
  id: string;
  name: string;
  location: string;
  website: string;
  contactPerson: string;
  mobile: string;
  email: string;
  companySize: string;
  numberOfEmployees: string;
  industry: string;
  ctc: string;
  status: "COLD" | "WARM" | "HOT" | "DRIVE_COMPLETED";
  approvalStatus: "PENDING" | "APPROVED" | "REJECTED";
  dateAdded: string;
  placementTeamMember: string;
  recruiter: string;
  jobRole: string;
  jd: string;
  jdPdf: string;
  driveStatus: string;
  placedStudentsCount: number;
  placedStudentsDetails: string;
  archived: boolean;
  
  // Extended fields
  companyType?: string;
  hrName?: string;
  hrEmail?: string;
  hrPhone?: string;
  description?: string;
  jobRoles?: string;
  requiredSkills?: string;
  salaryPackage?: string;
  jobType?: string;
  openPositions?: number;
  eligibilityCriteria?: string;
  companyStatus?: string;
}


export const INITIAL_COMPANY_CSV_DATA: CompanyRecord[] = [
  {
    "id": "1",
    "name": "Google India",
    "location": "Bengaluru, India",
    "website": "https://careers.google.com",
    "contactPerson": "Adithya Venkatesh (RCAS2024BCS011)",
    "mobile": "+91 80 6721 8000",
    "email": "campus-recruitment@google.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 24.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Adithya Venkatesh",
    "jobRole": "Software Engineer - Campus Specialist",
    "jd": "Design and implement scalable distributed software, algorithms, and core backend infrastructure.",
    "jdPdf": "https://example.com/jd/google-sde-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Adithya Venkatesh (RCAS2024BCS011)",
    "archived": false
  },
  {
    "id": "2",
    "name": "Microsoft India",
    "location": "Hyderabad, India",
    "website": "https://careers.microsoft.com",
    "contactPerson": "Sneha Muralidharan (RTC2024BCS012)",
    "mobile": "+91 40 6695 0000",
    "email": "university-india@microsoft.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 21.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Sneha Muralidharan",
    "jobRole": "Software Engineer - Azure Cloud",
    "jd": "Develop high-throughput cloud microservices, Azure integrations, and hyper-scale telemetry tools.",
    "jdPdf": "https://example.com/jd/microsoft-azure-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Sneha Muralidharan (RTC2024BCS012)",
    "archived": false
  },
  {
    "id": "3",
    "name": "Amazon Development Centre",
    "location": "Bengaluru, India",
    "website": "https://amazon.jobs",
    "contactPerson": "Rohit Balaji (RCAS2024BIT011)",
    "mobile": "+91 80 4103 0000",
    "email": "india-campus-hire@amazon.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 19.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Rohit Balaji",
    "jobRole": "Software Development Engineer (SDE-1)",
    "jd": "Build fault-tolerant multi-tier architecture, automated order fulfillment engines, and distributed APIs.",
    "jdPdf": "https://example.com/jd/amazon-sde1-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Rohit Balaji (RCAS2024BIT011)",
    "archived": false
  },
  {
    "id": "4",
    "name": "Amazon Web Services (AWS)",
    "location": "Bengaluru, India",
    "website": "https://aws.amazon.com/careers",
    "contactPerson": "Harini Natarajan (RTC2024BCY011)",
    "mobile": "+91 80 4103 0001",
    "email": "aws-university-in@amazon.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 17.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Harini Natarajan",
    "jobRole": "Cloud Support Associate - DevOps & Sec",
    "jd": "Triage complex AWS cloud infrastructure, configure VPCs, IAM policies, and infrastructure-as-code.",
    "jdPdf": "https://example.com/jd/aws-cloud-support-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Harini Natarajan (RTC2024BCY011)",
    "archived": false
  },
  {
    "id": "5",
    "name": "Adobe Systems",
    "location": "Noida, India",
    "website": "https://adobe.com/careers",
    "contactPerson": "Varshini Ramesh (RCAS2024BCS013)",
    "mobile": "+91 120 444 4700",
    "email": "india-ur@adobe.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 16.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Varshini Ramesh",
    "jobRole": "Member of Technical Staff - Creative Cloud",
    "jd": "Architect client-side rendering engines, WebAssembly integrations, and high-performance cloud assets.",
    "jdPdf": "https://example.com/jd/adobe-mts-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Varshini Ramesh (RCAS2024BCS013)",
    "archived": false
  },
  {
    "id": "6",
    "name": "Cisco Systems",
    "location": "Bengaluru, India",
    "website": "https://jobs.cisco.com",
    "contactPerson": "Akash Subramanian (RTC2024BEC011)",
    "mobile": "+91 80 4426 0000",
    "email": "university-hiring@cisco.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 15.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Akash Subramanian",
    "jobRole": "Network Security Engineer",
    "jd": "Design and maintain zero-trust enterprise firewalls, automated telemetry, and SD-WAN networks.",
    "jdPdf": "https://example.com/jd/cisco-netsec-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Akash Subramanian (RTC2024BEC011)",
    "archived": false
  },
  {
    "id": "7",
    "name": "Qualcomm India",
    "location": "Chennai, India",
    "website": "https://qualcomm.com/careers",
    "contactPerson": "Divya Lakshmi (RCAS2024BCY002)",
    "mobile": "+91 44 6612 0000",
    "email": "campus-india@qualcomm.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 14.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Divya Lakshmi",
    "jobRole": "Firmware & Embedded Security Engineer",
    "jd": "Develop low-level cryptographic microcode, ARM hardware security modules, and bootloader integrity.",
    "jdPdf": "https://example.com/jd/qualcomm-firmware-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Divya Lakshmi (RCAS2024BCY002)",
    "archived": false
  },
  {
    "id": "8",
    "name": "Salesforce India",
    "location": "Hyderabad, India",
    "website": "https://salesforce.com/careers",
    "contactPerson": "Gautham Krishna (RTC2024BIT012)",
    "mobile": "+91 40 6902 0000",
    "email": "futureforce-india@salesforce.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 13.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Gautham Krishna",
    "jobRole": "Associate Software Engineer",
    "jd": "Build scalable multi-tenant Apex apps, Lightning Web Components, and enterprise CRM workflow pipelines.",
    "jdPdf": "https://example.com/jd/salesforce-ase-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Gautham Krishna (RTC2024BIT012)",
    "archived": false
  },
  {
    "id": "9",
    "name": "CrowdStrike India",
    "location": "Pune, India",
    "website": "https://crowdstrike.com/careers",
    "contactPerson": "Abishek M (RCAS2024BCY004), Deepak Chandran (RTC2024BCY012)",
    "mobile": "+91 20 6710 0000",
    "email": "university@crowdstrike.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 13.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Abishek M",
    "jobRole": "Threat Intelligence Specialist",
    "jd": "Perform reverse engineering of malware payloads, identify threat actors, and author Falcon detections.",
    "jdPdf": "https://example.com/jd/crowdstrike-threat-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 2,
    "placedStudentsDetails": "Abishek M (RCAS2024BCY004), Deepak Chandran (RTC2024BCY012)",
    "archived": false
  },
  {
    "id": "10",
    "name": "Texas Instruments",
    "location": "Bengaluru, India",
    "website": "https://ti.com/careers",
    "contactPerson": "Ananya Rao (RCAS2024BEC002)",
    "mobile": "+91 80 2509 9000",
    "email": "india-campus@ti.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 11.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Ananya Rao",
    "jobRole": "Hardware & Embedded Systems Trainee",
    "jd": "Design mixed-signal PCB architectures, embedded microcontrollers, and perform digital signal processing.",
    "jdPdf": "https://example.com/jd/ti-embedded-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Ananya Rao (RCAS2024BEC002)",
    "archived": false
  },
  {
    "id": "11",
    "name": "Flipkart",
    "location": "Bengaluru, India",
    "website": "https://flipkartcareers.com",
    "contactPerson": "Pooja Sundaram (RTC2024BCS014)",
    "mobile": "+91 80 4208 0000",
    "email": "campusrelations@flipkart.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 11.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Pooja Sundaram",
    "jobRole": "Associate Software Engineer - Supply Chain",
    "jd": "Design warehouse inventory dispatch engines, real-time tracking queues, and high-throughput Kafka streaming.",
    "jdPdf": "https://example.com/jd/flipkart-ase-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Pooja Sundaram (RTC2024BCS014)",
    "archived": false
  },
  {
    "id": "12",
    "name": "Palo Alto Networks",
    "location": "Bengaluru, India",
    "website": "https://paloaltonetworks.com/careers",
    "contactPerson": "Naveen Kumar (RCAS2024BCY001)",
    "mobile": "+91 80 6112 0000",
    "email": "india-recruiting@paloaltonetworks.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 10.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Naveen Kumar",
    "jobRole": "SOC & Cyber Defense Analyst",
    "jd": "Monitor enterprise SOC incidents, analyze firewall logs, and configure automated Cortex XSOAR playbooks.",
    "jdPdf": "https://example.com/jd/paloalto-soc-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Naveen Kumar (RCAS2024BCY001)",
    "archived": false
  },
  {
    "id": "13",
    "name": "Infosys",
    "location": "Mysuru, India",
    "website": "https://infosys.com/careers",
    "contactPerson": "Dinesh Kumar T (RTC2024BCS005)",
    "mobile": "+91 821 240 4101",
    "email": "specialisthire@infosys.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 9.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Dinesh Kumar T",
    "jobRole": "Specialist Programmer (Power Programmer)",
    "jd": "Develop complex full-stack microservices using Spring Boot, React, and containerized deployment workflows.",
    "jdPdf": "https://example.com/jd/infosys-sp-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Dinesh Kumar T (RTC2024BCS005)",
    "archived": false
  },
  {
    "id": "14",
    "name": "Zoho Corporation",
    "location": "Chennai, India",
    "website": "https://zoho.com/careers",
    "contactPerson": "INBAVARUNAN S (RCAS2024BCY046), Manoj Prabhakar (RTC2024BCY013)",
    "mobile": "+91 44 6744 7070",
    "email": "recruitment@zohocorp.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 8.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "INBAVARUNAN S",
    "jobRole": "Application Security Engineer",
    "jd": "Perform SAST/DAST web vulnerability assessments, OAuth security hardening, and code remediation.",
    "jdPdf": "https://example.com/jd/zoho-appsec-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 2,
    "placedStudentsDetails": "INBAVARUNAN S (RCAS2024BCY046), Manoj Prabhakar (RTC2024BCY013)",
    "archived": false
  },
  {
    "id": "15",
    "name": "Deloitte USI",
    "location": "Hyderabad, India",
    "website": "https://deloitte.com/careers",
    "contactPerson": "Sanjay Kumar (RCAS2024BBA001)",
    "mobile": "+91 40 7125 0000",
    "email": "usiurrecruiting@deloitte.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 7.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Sanjay Kumar",
    "jobRole": "Business Technology Analyst",
    "jd": "Analyze IT architecture workflows, develop enterprise BI dashboards, and support ERP migrations.",
    "jdPdf": "https://example.com/jd/deloitte-bta-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Sanjay Kumar (RCAS2024BBA001)",
    "archived": false
  },
  {
    "id": "16",
    "name": "Tata Consultancy Services",
    "location": "Chennai, India",
    "website": "https://tcs.com/careers",
    "contactPerson": "Meena Devi (RTC2024BIT001)",
    "mobile": "+91 44 6616 8888",
    "email": "campus.recruitment@tcs.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 7.0 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Meena Devi",
    "jobRole": "Systems Engineer - Digital",
    "jd": "Implement cloud-native enterprise services, CI/CD automated build pipelines, and automated QA testing.",
    "jdPdf": "https://example.com/jd/tcs-digital-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Meena Devi (RTC2024BIT001)",
    "archived": false
  },
  {
    "id": "17",
    "name": "Wipro Digital",
    "location": "Bengaluru, India",
    "website": "https://careers.wipro.com",
    "contactPerson": "Swetha Mohan (RCAS2024BCY003)",
    "mobile": "+91 80 2844 0011",
    "email": "manager.campus@wipro.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 6.8 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Swetha Mohan",
    "jobRole": "Cyber Defense Analyst",
    "jd": "Coordinate incident response lifecycles, conduct vulnerability remediation, and manage endpoint security.",
    "jdPdf": "https://example.com/jd/wipro-cyber-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Swetha Mohan (RCAS2024BCY003)",
    "archived": false
  },
  {
    "id": "18",
    "name": "Cognizant Technology Solutions",
    "location": "Coimbatore, India",
    "website": "https://cognizant.com/careers",
    "contactPerson": "Vishal Anand (RTC2024BIT002)",
    "mobile": "+91 422 664 5000",
    "email": "campusconnection@cognizant.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 6.5 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Vishal Anand",
    "jobRole": "Programmer Analyst Trainee",
    "jd": "Build scalable frontend interfaces with React/Next.js and maintain PostgreSQL relational databases.",
    "jdPdf": "https://example.com/jd/cognizant-pat-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Vishal Anand (RTC2024BIT002)",
    "archived": false
  },
  {
    "id": "19",
    "name": "HDFC Bank",
    "location": "Mumbai, India",
    "website": "https://hdfcbank.com/careers",
    "contactPerson": "Keerthana R (RCAS2024BBA002)",
    "mobile": "+91 22 6652 1000",
    "email": "campusrecruitment@hdfcbank.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 6.2 LPA",
    "status": "DRIVE_COMPLETED",
    "approvalStatus": "APPROVED",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Keerthana R",
    "jobRole": "Management Trainee - Tech FinOps",
    "jd": "Oversee digital banking operations, credit score automation models, and compliance reporting.",
    "jdPdf": "https://example.com/jd/hdfc-mt-2027.pdf",
    "driveStatus": "Completed",
    "placedStudentsCount": 1,
    "placedStudentsDetails": "Keerthana R (RCAS2024BBA002)",
    "archived": false
  },
  {
    "id": "20",
    "name": "Oracle India",
    "location": "Bengaluru, India",
    "website": "https://oracle.com/careers",
    "contactPerson": "Upcoming Drive - Shortlisting Stage",
    "mobile": "+91 80 4327 0000",
    "email": "campus_india@oracle.com",
    "companySize": "5,000+ Employees",
    "numberOfEmployees": "5000+",
    "industry": "Software & Technology",
    "ctc": "\u20b9 12.5 LPA",
    "status": "WARM",
    "approvalStatus": "PENDING",
    "dateAdded": "2026-08-01",
    "placementTeamMember": "Placement Director",
    "recruiter": "Upcoming Drive - Shortlisting Stage",
    "jobRole": "Associate Cloud Consultant",
    "jd": "Assist enterprise clients with Oracle Cloud Infrastructure (OCI) architecture and automated database migration.",
    "jdPdf": "https://example.com/jd/oracle-oci-2027.pdf",
    "driveStatus": "Ongoing",
    "placedStudentsCount": 0,
    "placedStudentsDetails": "Upcoming Drive - Shortlisting Stage",
    "archived": false
  }
];
