import { StoredJD } from "@/services/jdService";

const now = new Date().toISOString();

export const INITIAL_JDS: StoredJD[] = [
  // TCS
  {
    id: "JD001",
    filename: "TCS_Software_Developer.pdf",
    company: "TCS",
    jobTitle: "Software Developer",
    location: "Chennai",
    experience: "0-2 years",
    education: "B.E/B.Tech/MCA in Computer Science or related field",
    salary: "Not specified",
    openings: "Not specified",
    industry: "IT Services",
    jobType: "Full-time",
    skills: ["Java", "Python", "SQL", "Data Structures", "Algorithms", "Git"],
    preferredSkills: [],
    responsibilities: [
      "Develop and maintain software applications.",
      "Write clean and maintainable code.",
      "Work with development and testing teams.",
      "Debug and resolve software issues.",
      "Participate in code reviews.",
      "Work with databases and APIs."
    ],
    eligibility: ["B.E/B.Tech/MCA in Computer Science or related field."],
    keywords: ["Software Development", "Backend", "Programming", "Database", "API", "Agile"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD002",
    filename: "TCS_Data_Analyst.pdf",
    company: "TCS",
    jobTitle: "Data Analyst",
    location: "Chennai/Bengaluru",
    experience: "0-2 years",
    education: "B.E/B.Tech/B.Sc/M.Sc/MCA or related degree",
    salary: "Not specified",
    openings: "Not specified",
    industry: "IT Services",
    jobType: "Full-time",
    skills: ["Python", "SQL", "Excel", "Power BI", "Statistics"],
    preferredSkills: [],
    responsibilities: [
      "Analyze business datasets.",
      "Create dashboards and reports.",
      "Identify trends and patterns.",
      "Clean and preprocess data.",
      "Present analytical insights to teams."
    ],
    eligibility: ["B.E/B.Tech/B.Sc/M.Sc/MCA or related degree."],
    keywords: ["Data Analysis", "Reporting", "Dashboards", "Visualization", "Data Cleaning"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD003",
    filename: "TCS_AIML_Engineer.pdf",
    company: "TCS",
    jobTitle: "AI/ML Engineer",
    location: "Not specified",
    experience: "0-2 years",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "IT Services",
    jobType: "Full-time",
    skills: ["Python", "Machine Learning", "Pandas", "NumPy", "Scikit-learn", "SQL"],
    preferredSkills: [],
    responsibilities: [
      "Build machine learning models.",
      "Prepare and analyze datasets.",
      "Evaluate model performance.",
      "Develop AI-based solutions.",
      "Work with engineering and business teams."
    ],
    eligibility: [],
    keywords: ["AI", "ML", "Artificial Intelligence", "Modeling", "Data Science", "Algorithms"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  
  // Infosys
  {
    id: "JD004",
    filename: "Infosys_Java_Developer.pdf",
    company: "Infosys",
    jobTitle: "Java Developer",
    location: "Bengaluru",
    experience: "0-2 years",
    education: "B.E/B.Tech/MCA",
    salary: "Not specified",
    openings: "Not specified",
    industry: "IT Services",
    jobType: "Full-time",
    skills: ["Java", "Spring Boot", "SQL", "REST API", "Git"],
    preferredSkills: [],
    responsibilities: [
      "Develop Java applications.",
      "Build REST APIs.",
      "Debug application issues.",
      "Work with databases.",
      "Participate in Agile development."
    ],
    eligibility: ["B.E/B.Tech/MCA"],
    keywords: ["Backend", "Java", "Spring", "API", "Microservices", "Agile"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD005",
    filename: "Infosys_Full_Stack_Developer.pdf",
    company: "Infosys",
    jobTitle: "Full Stack Developer",
    location: "Not specified",
    experience: "0-2 years",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "IT Services",
    jobType: "Full-time",
    skills: ["JavaScript", "React", "Node.js", "HTML", "CSS", "SQL"],
    preferredSkills: [],
    responsibilities: [
      "Develop frontend and backend applications.",
      "Build responsive web interfaces.",
      "Create APIs.",
      "Integrate databases.",
      "Test and deploy applications."
    ],
    eligibility: [],
    keywords: ["Full Stack", "Frontend", "Backend", "Web Development", "UI/UX", "Deployment"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD006",
    filename: "Infosys_Data_Scientist.pdf",
    company: "Infosys",
    jobTitle: "Data Scientist",
    location: "Not specified",
    experience: "0-2 years",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "IT Services",
    jobType: "Full-time",
    skills: ["Python", "Machine Learning", "Statistics", "SQL", "Pandas", "NumPy"],
    preferredSkills: [],
    responsibilities: [
      "Analyze large datasets.",
      "Build predictive models.",
      "Perform exploratory data analysis.",
      "Develop machine learning solutions.",
      "Communicate insights to stakeholders."
    ],
    eligibility: [],
    keywords: ["Data Science", "Machine Learning", "Analytics", "Predictive Modeling", "Statistics", "Big Data"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },

  // CodePulse
  {
    id: "JD007",
    filename: "CodePulse_Full_Stack_Developer.pdf",
    company: "CodePulse",
    jobTitle: "Full Stack Developer",
    location: "Bengaluru",
    experience: "0-2 years",
    education: "B.E/B.Tech/MCA or equivalent",
    salary: "Not specified",
    openings: "Not specified",
    industry: "Software / Technology",
    jobType: "Full-time",
    skills: ["React", "JavaScript", "Node.js", "MongoDB", "REST API", "Git"],
    preferredSkills: [],
    responsibilities: [
      "Build and improve web applications.",
      "Develop frontend and backend features.",
      "Integrate APIs.",
      "Fix bugs and improve application performance.",
      "Work closely with the product team."
    ],
    eligibility: ["B.E/B.Tech/MCA or equivalent"],
    keywords: ["MERN", "Full Stack", "Startup", "Web Development", "API", "Frontend", "Backend"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD008",
    filename: "CodePulse_AI_Engineer.pdf",
    company: "CodePulse",
    jobTitle: "AI Engineer",
    location: "Not specified",
    experience: "Not specified",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "Artificial Intelligence",
    jobType: "Full-time",
    skills: ["Python", "Machine Learning", "Generative AI", "APIs", "SQL"],
    preferredSkills: [],
    responsibilities: [
      "Develop AI-powered features.",
      "Experiment with machine learning models.",
      "Integrate AI APIs.",
      "Build prototypes.",
      "Evaluate AI model performance."
    ],
    eligibility: [],
    keywords: ["GenAI", "LLMs", "AI", "Machine Learning", "Startup", "Prototyping", "Integration"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },

  // Krea Data Edge
  {
    id: "JD009",
    filename: "Krea_Data_Engineer.pdf",
    company: "Krea Data Edge",
    jobTitle: "Data Engineer",
    location: "Bengaluru",
    experience: "0-2 years",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "Data Analytics",
    jobType: "Full-time",
    skills: ["Python", "SQL", "ETL", "Pandas", "Data Pipelines"],
    preferredSkills: [],
    responsibilities: [
      "Build data pipelines.",
      "Clean and transform datasets.",
      "Work with SQL databases.",
      "Automate data processing.",
      "Support analytics teams."
    ],
    eligibility: [],
    keywords: ["Data Engineering", "ETL", "Pipelines", "Automation", "Big Data", "Startup"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD010",
    filename: "Krea_ML_Engineer.pdf",
    company: "Krea Data Edge",
    jobTitle: "Machine Learning Engineer",
    location: "Not specified",
    experience: "0-2 years",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "AI / Data Science",
    jobType: "Full-time",
    skills: ["Python", "Machine Learning", "Scikit-learn", "Pandas", "NumPy", "SQL"],
    preferredSkills: [],
    responsibilities: [
      "Develop machine learning models.",
      "Prepare training datasets.",
      "Evaluate model accuracy.",
      "Deploy ML solutions.",
      "Work with data scientists and engineers."
    ],
    eligibility: [],
    keywords: ["Machine Learning", "Model Deployment", "Data Science", "Training", "Startup", "Algorithms"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "JD011",
    filename: "Krea_Data_Analyst.pdf",
    company: "Krea Data Edge",
    jobTitle: "Data Analyst",
    location: "Not specified",
    experience: "0-2 years",
    education: "Not specified",
    salary: "Not specified",
    openings: "Not specified",
    industry: "Data Analytics",
    jobType: "Full-time",
    skills: ["SQL", "Python", "Excel", "Power BI", "Statistics"],
    preferredSkills: [],
    responsibilities: [
      "Analyze business data.",
      "Build dashboards.",
      "Generate reports.",
      "Identify business trends.",
      "Provide actionable insights."
    ],
    eligibility: [],
    keywords: ["Data Analysis", "Dashboards", "Business Intelligence", "Startup", "Reporting", "Visualization"],
    recruitmentProcess: [],
    status: "ACTIVE",
    analysisStatus: "COMPLETED",
    createdAt: now,
    updatedAt: now,
  }
];
