export const MOCK_STUDENTS = [
  {
    id: "R001",
    rollNumber: "R001",
    name: "Keerthana",
    department: "CSE",
    gender: "Female",
    residence: "Hostler",
    studentType: "Hostler",
    sslcPercentage: 92.4,
    hscPercentage: 89.6,
    ugPercentage: "B.E. CSE",
    ugPercentageNum: 88,
    pgPercentage: "M.Tech",
    github: "keerthana-dev",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "keerthana@example.com",
    mobile: "9000000001",
    yearOfGraduation: 2026,
    placementStatus: "PLACED",
    resumeScore: 92,
    isArchived: false,
    applications: 14,
    interviews: 6,
    offers: 2,
  },
  {
    id: "R002",
    rollNumber: "R002",
    name: "Vimal Kumar",
    department: "ECE",
    gender: "Male",
    residence: "Day Scholar",
    studentType: "Day Scholar",
    sslcPercentage: 88.5,
    hscPercentage: 86.2,
    ugPercentage: "B.E. ECE",
    ugPercentageNum: 84,
    pgPercentage: "",
    github: "vimal-kumar-dev",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "vimal.kumar@example.com",
    mobile: "9000000002",
    yearOfGraduation: 2026,
    placementStatus: "UNPLACED",
    resumeScore: 78,
    isArchived: false,
    applications: 8,
    interviews: 2,
    offers: 0,
  },
  {
    id: "R003",
    rollNumber: "R003",
    name: "Thvin Kumar",
    department: "CSE",
    gender: "Male",
    residence: "Hostler",
    studentType: "Hostler",
    sslcPercentage: 91.0,
    hscPercentage: 87.8,
    ugPercentage: "B.E. CSE",
    ugPercentageNum: 85,
    pgPercentage: "",
    github: "thvin-kumar",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "thvin.kumar@example.com",
    mobile: "9000000003",
    yearOfGraduation: 2026,
    placementStatus: "SHORTLISTED",
    resumeScore: 81,
    isArchived: false,
    applications: 10,
    interviews: 4,
    offers: 0,
  },
  {
    id: "R004",
    rollNumber: "R004",
    name: "Sharmila",
    department: "IT",
    gender: "Female",
    residence: "Day Scholar",
    studentType: "Day Scholar",
    sslcPercentage: 94.2,
    hscPercentage: 91.5,
    ugPercentage: "B.Tech IT",
    ugPercentageNum: 90,
    pgPercentage: "MCA",
    github: "sharmila-it",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "sharmila@example.com",
    mobile: "9000000004",
    yearOfGraduation: 2026,
    placementStatus: "PLACED",
    resumeScore: 95,
    isArchived: false,
    applications: 15,
    interviews: 8,
    offers: 3,
  },
  {
    id: "R005",
    rollNumber: "R005",
    name: "Lavanya",
    department: "CSE",
    gender: "Female",
    residence: "Hostler",
    studentType: "Hostler",
    sslcPercentage: 90.8,
    hscPercentage: 88.9,
    ugPercentage: "B.E. CSE",
    ugPercentageNum: 87,
    pgPercentage: "",
    github: "lavanya-codes",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "lavanya@example.com",
    mobile: "9000000005",
    yearOfGraduation: 2026,
    placementStatus: "SHORTLISTED",
    resumeScore: 84,
    isArchived: false,
    applications: 12,
    interviews: 3,
    offers: 0,
  },
  {
    id: "R006",
    rollNumber: "R006",
    name: "Gokilam",
    department: "ECE",
    gender: "Female",
    residence: "Day Scholar",
    studentType: "Day Scholar",
    sslcPercentage: 87.6,
    hscPercentage: 85.4,
    ugPercentage: "B.E. ECE",
    ugPercentageNum: 82,
    pgPercentage: "",
    github: "gokilam-tech",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "gokilam@example.com",
    mobile: "9000000006",
    yearOfGraduation: 2026,
    placementStatus: "UNPLACED",
    resumeScore: 75,
    isArchived: false,
    applications: 5,
    interviews: 1,
    offers: 0,
  },
  {
    id: "R007",
    rollNumber: "R007",
    name: "Harini",
    department: "IT",
    gender: "Female",
    residence: "Hostler",
    studentType: "Hostler",
    sslcPercentage: 93.1,
    hscPercentage: 90.2,
    ugPercentage: "B.Tech IT",
    ugPercentageNum: 89,
    pgPercentage: "M.Tech",
    github: "harini-dev",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "harini@example.com",
    mobile: "9000000007",
    yearOfGraduation: 2026,
    placementStatus: "PLACED",
    resumeScore: 91,
    isArchived: false,
    applications: 11,
    interviews: 5,
    offers: 1,
  },
  {
    id: "R008",
    rollNumber: "R008",
    name: "Vishal",
    department: "CSE",
    gender: "Male",
    residence: "Day Scholar",
    studentType: "Day Scholar",
    sslcPercentage: 85.9,
    hscPercentage: 83.7,
    ugPercentage: "B.E. CSE",
    ugPercentageNum: 80,
    pgPercentage: "",
    github: "vishal-codes",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "vishal@example.com",
    mobile: "9000000008",
    yearOfGraduation: 2026,
    placementStatus: "UNPLACED",
    resumeScore: 72,
    isArchived: false,
    applications: 6,
    interviews: 0,
    offers: 0,
  },
  {
    id: "R009",
    rollNumber: "R009",
    name: "Ajay Krishna",
    department: "EEE",
    gender: "Male",
    residence: "Hostler",
    studentType: "Hostler",
    sslcPercentage: 89.7,
    hscPercentage: 84.8,
    ugPercentage: "B.E. EEE",
    ugPercentageNum: 81,
    pgPercentage: "",
    github: "ajay-krishna",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "ajay.krishna@example.com",
    mobile: "9000000009",
    yearOfGraduation: 2026,
    placementStatus: "SHORTLISTED",
    resumeScore: 79,
    isArchived: false,
    applications: 9,
    interviews: 3,
    offers: 0,
  },
  {
    id: "R010",
    rollNumber: "R010",
    name: "Vishnu",
    department: "ECE",
    gender: "Male",
    residence: "Day Scholar",
    studentType: "Day Scholar",
    sslcPercentage: 86.4,
    hscPercentage: 82.9,
    ugPercentage: "B.E. ECE",
    ugPercentageNum: 78,
    pgPercentage: "MBA",
    github: "vishnu-tech",
    linkedin: "",
    portfolio: "",
    resumeLink: "#",
    selfIntroLink: "#",
    photoUrl: "",
    email: "vishnu@example.com",
    mobile: "9000000010",
    yearOfGraduation: 2026,
    placementStatus: "UNPLACED",
    resumeScore: 68,
    isArchived: false,
    applications: 4,
    interviews: 0,
    offers: 0,
  }
];

export const MOCK_RECRUITERS = [
  { id: "REC001", companyId: "C001", name: "Ananya Sharma", designation: "Talent Acquisition", email: "recruiter.tcs@example.com", mobile: "9000010001", linkedin: "" },
  { id: "REC002", companyId: "C002", name: "Rahul Kumar", designation: "Campus Recruiter", email: "recruiter.infosys@example.com", mobile: "9000010002", linkedin: "" },
  { id: "REC003", companyId: "C003", name: "Priya Menon", designation: "HR Recruiter", email: "recruiter.accenture@example.com", mobile: "9000010003", linkedin: "" },
  { id: "REC004", companyId: "C004", name: "Arjun Rao", designation: "Talent Partner", email: "recruiter.zoho@example.com", mobile: "9000010004", linkedin: "" },
  { id: "REC005", companyId: "C005", name: "Sneha Iyer", designation: "Campus Hiring", email: "recruiter.wipro@example.com", mobile: "9000010005", linkedin: "" }
];

export const MOCK_PIPELINE = [
  { id: "P001", companyId: "C001", companyName: "TCS", driveStatus: "Upcoming", currentStage: "Registration", driveDate: "2026-09-10", expectedHiring: 50 },
  { id: "P002", companyId: "C002", companyName: "Infosys", driveStatus: "Upcoming", currentStage: "JD Received", driveDate: "2026-09-15", expectedHiring: 40 },
  { id: "P003", companyId: "C003", companyName: "Accenture", driveStatus: "Active", currentStage: "Applications", driveDate: "2026-09-20", expectedHiring: 30 },
  { id: "P004", companyId: "C004", companyName: "Zoho", driveStatus: "Active", currentStage: "Assessment", driveDate: "2026-09-25", expectedHiring: 15 },
  { id: "P005", companyId: "C005", companyName: "Wipro", driveStatus: "Completed", currentStage: "Interview", driveDate: "2026-08-30", expectedHiring: 35 }
];

export const MOCK_COMPANIES = [
  { id: "C001", name: "TCS", industry: "IT Services", location: "Chennai", website: "https://www.tcs.com", type: "MNC" },
  { id: "C002", name: "Infosys", industry: "IT Services", location: "Bengaluru", website: "https://www.infosys.com", type: "MNC" },
  { id: "C003", name: "Accenture", industry: "Consulting & IT", location: "Chennai", website: "https://www.accenture.com", type: "MNC" },
  { id: "C004", name: "Zoho", industry: "Software", location: "Chennai", website: "https://www.zoho.com", type: "Product" },
  { id: "C005", name: "Wipro", industry: "IT Services", location: "Bengaluru", website: "https://www.wipro.com", type: "MNC" },
  { id: "C006", name: "Cognizant", industry: "IT Services", location: "Chennai", website: "https://www.cognizant.com", type: "MNC" },
  { id: "C007", name: "HCLTech", industry: "IT Services", location: "Chennai", website: "https://www.hcltech.com", type: "MNC" },
  { id: "C008", name: "Freshworks", industry: "SaaS", location: "Chennai", website: "https://www.freshworks.com", type: "Product" },
  { id: "C009", name: "Capgemini", industry: "IT Services", location: "Bengaluru", website: "https://www.capgemini.com", type: "MNC" },
  { id: "C010", name: "Amazon", industry: "E-Commerce/Cloud", location: "Bengaluru", website: "https://www.amazon.com", type: "MNC" }
];

export const MOCK_JDS = [
  { id: "JD001", companyId: "C001", jobTitle: "Graduate Engineer Trainee", department: "CSE/IT", qualifications: "B.E/B.Tech", skillsRequired: "Java, SQL, Python", salary: "4.5 LPA", jdDocument: "" },
  { id: "JD002", companyId: "C002", jobTitle: "Systems Engineer", department: "CSE/IT", qualifications: "B.E/B.Tech", skillsRequired: "Java, SQL, Cloud", salary: "4.2 LPA", jdDocument: "" },
  { id: "JD003", companyId: "C003", jobTitle: "Associate Software Engineer", department: "CSE/IT", qualifications: "B.E/B.Tech", skillsRequired: "Java, Python, SQL", salary: "5 LPA", jdDocument: "" },
  { id: "JD004", companyId: "C004", jobTitle: "Software Developer", department: "CSE/IT", qualifications: "B.E/B.Tech", skillsRequired: "JavaScript, React, Java", salary: "6 LPA", jdDocument: "" },
  { id: "JD005", companyId: "C005", jobTitle: "Project Engineer", department: "CSE/ECE/IT", qualifications: "B.E/B.Tech", skillsRequired: "C, Java, SQL", salary: "4 LPA", jdDocument: "" }
];

export const MOCK_DRIVES = [
  { id: "D001", companyId: "C001", driveType: "Campus Drive", driveDate: "2026-09-10", venue: "College Campus", eligibility: "60%+", status: "Upcoming" },
  { id: "D002", companyId: "C002", driveType: "Campus Drive", driveDate: "2026-09-15", venue: "College Campus", eligibility: "65%+", status: "Upcoming" },
  { id: "D003", companyId: "C003", driveType: "Pool Drive", driveDate: "2026-09-20", venue: "Online", eligibility: "60%+", status: "Upcoming" },
  { id: "D004", companyId: "C004", driveType: "Campus Drive", driveDate: "2026-09-25", venue: "College Campus", eligibility: "70%+", status: "Active" },
  { id: "D005", companyId: "C005", driveType: "Campus Drive", driveDate: "2026-08-30", venue: "College Campus", eligibility: "60%+", status: "Interview" }
];
